version: "3.5"
services:
  vsftpd:
    image: siyuwuxin/vsftpd-alpine:latest
    expose:
      - "30022-30100"
    ports:
      - "30020:20"
      - "30021:21"
      - "30022-30100:30022-30100"
    volumes:
      - ./ftp/:/home/ftp/:rw
      - ./logs/vsftpd/:/var/log/vsftpd/:rw
    environment:
      - FTP_USER=admin
      - FTP_PASS=notneedhere
      - PASV_ADDRESS=**IPv4**
      - PASV_MIN_PORT=30022
      - PASV_MAX_PORT=30100
